

services:
  krishna-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: krishna_agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY} # Ensure your .env file has the API key
    ports:
      - "5001:5001" # Adjust the port if needed
    volumes:
      - .:/app
    restart: unless-stopped

